Added CI Workflow
marcomagdy/psaltos pull request #6
Opened 2023-02-28 21:37 UTC by nardineshak

2023-03-02 18:10 UTC, marcomagdy requested changes, later dismissed
Thank you for doing the work @nardineshak.
This looks great, I left a couple of comments.

2023-03-02 18:10 UTC, marcomagdy commented on .github/workflows/pullrequestCI.yml
> +        dotnet-version: ['3.0', '3.1.x', '5.0.x' ]
We're using .net 7.0, so we should change these.

2023-03-02 18:10 UTC, marcomagdy commented on Psaltos.Tests/TestClassAttribute.cs
> +}
I don't think we need this class or file. You can remove it.

2023-03-02 18:10 UTC, marcomagdy commented on Psaltos.Tests/TestMethodAttribute.cs
> +    internal class TestMethodAttribute : Attribute
Same here, I don't think we need this file/class.

2023-03-02 18:10 UTC, marcomagdy commented on psaltos.csproj
> +    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
Nice. I remember googling for these :)

2023-03-04 20:36 UTC, AthanIsaac commented
LGTM

2023-03-04 20:36 UTC, AthanIsaac approved these changes

2023-03-04 20:49 UTC, merged